"project_id": "797314"
"api_token": "86a87563605177699a56405c402c6373e36e947d94790ae954953d89bf217ee06f754cbf0ddd5b02"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source": "/langs/en.toml",
    "translation": "/langs/%two_letters_code%.toml"
  },
]