"project_id": "797314"
"api_token": "<API_TOKEN>"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source": "/langs/en.toml",
    "translation": "/langs/%two_letters_code%.toml"
  },
]