[contact]
success = "Сообщение успешно отправлено разработчику."
failure = "Не удалось отправить сообщение разработчику. Пожалуйста, повторите попытку позже."

[config]
title = "Конфигурация"
description = "Настройте параметры"
