"""LLM routing and chat orchestration module."""

import logging
import tomllib
from datetime import datetime
from typing import Dict, Any

import discord
import litellm

from utils.config.app_config import LOGGER_NAME, BOTS_IDS
from utils.config.constants import AVAILABLE_MODELS, DEFAULT_MODEL
from utils.ai.selector import llm_selector
from utils.ai.litellm_utils import extract_litellm_error_message
from models.text.mistral import mistral_chat
from models.text.deepseek import deepseek_chat
from models.text.gemini import gemini_chat
from models.text.qwen import qwen_chat
from models.text.openai import openai_chat
from models.text.evilgpt import evilgpt_chat
from models.text.grok import grok_chat
from models.text.llama import llama_chat
from models.text.perplexity import perplexity_chat
from models.text.claude import claude_chat
from models.text.cohere import cohere_chat
from models.text.glm import glm_chat
from models.text.kimi import kimi_chat
from models.text.phi import phi_chat

logger = logging.getLogger(LOGGER_NAME)

# Mappings bots IDs to model names
BOTS_TO_MODELS = {v: k for k, v in BOTS_IDS.items()}

# Model routing table
MODEL_ROUTES = {
    "mistral": mistral_chat,
    "deepseek": deepseek_chat,
    "gemini": gemini_chat,
    "qwen": qwen_chat,
    "openai": openai_chat,
    "chatgpt": openai_chat,
    "evilgpt": evilgpt_chat,
    "grok": grok_chat,
    "llama": llama_chat,
    "perplexity": perplexity_chat,
    "claude": claude_chat,
    "cohere": cohere_chat,
    "command": cohere_chat,
    "glm": glm_chat,
    "kimi": kimi_chat,
    "phi": phi_chat
}


def get_base_preprompt() -> str:
    """Load base preprompt from configuration file.
    
    Returns:
        str: Base preprompt with system date/time appended.
        
    Raises:
        Exception: If config.toml cannot be read.
    """
    try:
        with open("config.toml", "rb") as file:
            config = tomllib.load(file)
        preprompt = config.get("preprompt", "")
        logger.debug("Preprompt loaded from config.toml")
        
        now = datetime.now()
        preprompt += f"\nDate: {now.strftime('%Y-%m-%d')}\nHour: CEST {now.strftime('%H:%M:%S')}\n"
        return preprompt
    except Exception as e:
        logger.error(f"Error loading preprompt: {str(e)}")
        raise


async def chat(
    messages: list[Dict[str, str]],
    bot: discord.Client,
    user: str,
    parameters: Dict[str, Any]
) -> Dict[str, Any] | str | bytes:
    """Route chat request to appropriate LLM model.
    
    Args:
        messages: List of message dicts with role and content.
        bot: Discord bot instance for ID extraction.
        user: Discord user display name.
        parameters: Dict containing model selection and LLM parameters.
        
    Returns:
        Response from selected LLM (dict, str, or bytes for images).
        
    Raises:
        Exception: If chat fails after all fallbacks.
    """
    try:
        model = parameters.get("model", bot.user.id if isinstance(bot, discord.Client) else bot.id)
        
        # Get human-readable model name for logging
        model_name_for_log = model
        if isinstance(model, str) and model in MODEL_ROUTES:
            model_name_for_log = model
        elif isinstance(model, str) and model in BOTS_TO_MODELS:
            model_name_for_log = BOTS_TO_MODELS[model]
        elif isinstance(model, int) and model in BOTS_TO_MODELS:
            # Convert bot ID to model name
            model_name_for_log = BOTS_TO_MODELS.get(model, f"Bot#{model}")
        
        logger.info(f"Chat request - model: {str(model_name_for_log).capitalize()}.")
        
        # Route by model ID or name
        model_id = BOTS_IDS.get(model) if isinstance(model, str) else model
        
        for model_name, handler in MODEL_ROUTES.items():
            if model == model_id or model == model_name or model_name == model:
                logger.debug(f"Using {model_name} model")
                response = await handler(messages, parameters)
                logger.debug(f"Response generated by {model_name}")
                return response
        
        # Fallback: use LLM selector to choose best model
        logger.debug("Model not recognized, using LLM selector")
        selected_model = await llm_selector(messages[-1]['content'])
        logger.info(f"Selected model: {selected_model}")
        
        if selected_model in MODEL_ROUTES:
            response = await MODEL_ROUTES[selected_model](messages, parameters)
            logger.debug(f"Response generated by {selected_model}")
            return response
        
        # Final fallback to Llama
        logger.warning(f"Model '{selected_model}' not found, using Llama fallback")
        response = await llama_chat(messages, parameters)
        return response
        
    except (litellm.RateLimitError, litellm.APIError, litellm.APIConnectionError) as e:
        # Handle litellm-specific errors with cleaner messages
        error_msg = extract_litellm_error_message(e)
        logger.error(f"LLM API error: {error_msg}")
        raise Exception(error_msg) from e
    except Exception as e:
        logger.error(f"Chat error: {str(e)}", exc_info=True)
        raise
